### PR TITLE
Update to 1.4, Use Maven for build system, remove binaries from archive

### PR DESCRIPTION
**Pull request by jbcpollak**
Hello,

We have updated Nexmo's JAVA library to use Maven as the build system. This is a first step towards deploying the library to the global Maven repository, which will make the library more accessible to other users.

This version also updates the GitHub version to 1.4, which is the version available on your website. (GitHub currently has 1.2).

I have bumped the version to 1.5-SNAPSHOT, since 1.4 has already been released. The source code has been moved to the maven standard directory structure, and the build directory has been removed and ignored.

I would recommend in the future also removing the javadoc and compiled .jar file from the source code.

### CODE REVIEW

**Comment by daniele-athome** [comment]
I don't think Nexmo maintains this repository. It seems to me it's a bare mirror of their source code.

**Comment by jbcpollak** [comment]
@daniele-athome - probably not, thats why I had to update this code to 1.4...

**Comment by daniele-athome** [comment]
@jbcpollak could you rebase your modifications to latest master please? I might be able to get this merged.

**Comment by jbcpollak** [comment]
This version had too much other stuff in it to get a rebase or merge to work cleanly, and much of the changes were obsolete. I created a new PR with just the Maven changes:

https://github.com/Nexmo/nexmo-java-sdk/pull/6

**Comment by daniele-athome** [comment]
Thanks @jbcpollak! There is some work pending for Java 1.6 compatibility (I need to get an answer from Nexmo about that). After the Java version matter is settled we can actually request merge for this.

**Comment by dschulz** [comment]
Hi,
Firstly, thanks for your time and effort guys!
Any news on this? Using the Nexmo Java API is too cumbersome without maven support.

**Pull request closed without merging**
